server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: localhost
    port: 8761
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

spring:
  datasource:
    username: postgres
    password: 123#dev
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6551/postgres
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
